name = "Justifiable"
version = "0.1.0"
defaultTargets = ["Justifiable"]

[[lean_lib]]
name = "Justifiable"

[[require]]
name = "aeneas"
git = "https://github.com/cryspen/aeneas"
rev = "nightly-2026.09.03-6852e64"
subDir = "backends/lean"

[[require]]
name = "hax"
git = "https://github.com/cryspen/hax-lean"
rev = "v0.3.17"
