-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verity_chain]: function definitions
import Aeneas
import CoreModels
import Merkle.Extraction.Types
import Merkle.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace verity_chain

/-- [verity_chain::merkle::hash_tree_root]:
    Source: 'crates/verity-chain/src/merkle.rs', lines 12:0-14:1
    Visibility: public -/
def merkle.hash_tree_root
  {T : Type} (libssz_merkleHashTreeRootInst : libssz_merkle.HashTreeRoot T)
  (value : T) :
  RustM (Array Std.U8 32#usize)
  := do
  libssz_merkleHashTreeRootInst.hash_tree_root
    libssz_merkle.Sha2Hasher.Insts.Libssz_merkleSha256Hasher value ()

end verity_chain
