-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verity_chain]: external functions.
-- This is a template file: hax seeded Pure/Assumptions/FunsExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
import Pure.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open verity_chain

/-- [verity_chain::slot_clock::{impl core::fmt::Debug for verity_chain::slot_clock::SlotClock}::fmt]:
    Source: 'crates/verity-chain/src/slot_clock.rs', lines 17:9-17:14
    Visibility: public -/
axiom slot_clock.SlotClock.Insts.CoreFmtDebug.fmt
  :
  slot_clock.SlotClock → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

