-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verity_chain]: type definitions
import Aeneas
import CoreModels
import Pure.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace verity_chain

/-- [verity_chain::error::RejectionReason]
    Source: 'crates/verity-chain/src/error.rs', lines 29:0-96:1
    Visibility: public -/
@[discriminant isize]
inductive error.RejectionReason where
| BlockSlotNotInFuture : error.RejectionReason
| BlockSlotGapTooLarge : error.RejectionReason
| BlockSlotMismatch : error.RejectionReason
| BlockOlderThanLatestHeader : error.RejectionReason
| ParentRootMismatch : error.RejectionReason
| StateRootMismatch : error.RejectionReason
| WrongProposer : error.RejectionReason
| EmptyValidatorRegistry : error.RejectionReason
| ValidatorIndexOutOfRange : error.RejectionReason
| TooManyAttestationData : error.RejectionReason
| EmptyAggregationBits : error.RejectionReason
| JustificationVotesLengthMismatch : error.RejectionReason
| JustifiedSlotOutOfRange : error.RejectionReason
| ZeroHashJustificationRoot : error.RejectionReason
| AnchorStateRootMismatch : error.RejectionReason
| UnknownParentBlock : error.RejectionReason
| BlockTooFarInFuture : error.RejectionReason
| DuplicateAttestationData : error.RejectionReason
| UnknownSourceBlock : error.RejectionReason
| UnknownTargetBlock : error.RejectionReason
| UnknownHeadBlock : error.RejectionReason
| SourceAfterTarget : error.RejectionReason
| HeadOlderThanTarget : error.RejectionReason
| SourceSlotMismatch : error.RejectionReason
| TargetSlotMismatch : error.RejectionReason
| HeadSlotMismatch : error.RejectionReason
| SourceNotAncestorOfTarget : error.RejectionReason
| TargetNotAncestorOfHead : error.RejectionReason
| HeadNotDescendantOfFinalized : error.RejectionReason
| AttestationTooFarInFuture : error.RejectionReason
| AttestationSlotBeforeHead : error.RejectionReason
| ValidatorNotInState : error.RejectionReason
| InvalidSignature : error.RejectionReason

/-- [verity_chain::justification::extend_justified_slots_to::closure]
    Source: 'crates/verity-chain/src/justification.rs', lines 132:21-132:65 -/
@[reducible]
def justification.extend_justified_slots_to.closure := Unit

/-- [verity_chain::slot_clock::SlotClock]
    Source: 'crates/verity-chain/src/slot_clock.rs', lines 18:0-20:1
    Visibility: public -/
structure slot_clock.SlotClock where
  genesis_time : Std.U64

end verity_chain
