-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verity_justifiability]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import VerityJustifiability.Types
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open verity_justifiability

/-- [core::num::{u128}::isqrt]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3654:8-3654:40
    Name pattern: [core::num::{u128}::isqrt]
    Visibility: public -/
@[rust_fun "core::num::{u128}::isqrt"]
axiom core.num.U128.isqrt : Std.U128 → RustM Std.U128

