-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verity_justifiability]: type definitions
import Aeneas
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace verity_justifiability

/-- [verity_justifiability::Slot]
    Source: 'crates/verity-justifiability/src/lib.rs', lines 10:0-10:25
    Visibility: public -/
@[reducible]
def Slot := Std.U64

end verity_justifiability
