-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [verity_justifiability]: function definitions
import Aeneas
import CoreModels
import Justifiable.Extraction.Types
import Justifiable.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace verity_justifiability

/-- [verity_justifiability::IMMEDIATE_JUSTIFICATION_WINDOW]
    Source: 'crates/verity-justifiability/src/lib.rs', lines 13:0-13:50
    Visibility: public -/
@[global_simps, irreducible]
def IMMEDIATE_JUSTIFICATION_WINDOW : Std.U64 := 5#u64

/-- [verity_justifiability::is_perfect_square]:
    Source: 'crates/verity-justifiability/src/lib.rs', lines 44:0-47:1 -/
def is_perfect_square (value : Std.U128) : RustM Bool := do
  let root ← core.num.U128.isqrt value
  let i ← root * root
  ok (i = value)

/-- [verity_justifiability::is_justifiable_after]:
    Source: 'crates/verity-justifiability/src/lib.rs', lines 21:0-42:1
    Visibility: public -/
def is_justifiable_after (slot : Slot) (finalized : Slot) : RustM Bool := do
  if slot < finalized
  then ok false
  else
    let delta ← slot - finalized
    if delta <= IMMEDIATE_JUSTIFICATION_WINDOW
    then ok true
    else
      let i ← core.U128.Insts.CoreConvertFromU64.from delta
      let b ← is_perfect_square i
      if b
      then ok true
      else
        let i1 ← 4#u128 * i
        let discriminant ← i1 + 1#u128
        let b1 ← is_perfect_square discriminant
        if b1
        then
          let i2 ← core.num.U128.isqrt discriminant
          let i3 ← i2 % 2#u128
          ok (i3 = 1#u128)
        else ok false

end verity_justifiability
